# 在您的 fork 仓库中，创建一个名为 `.github/workflows/sync.yml` 的文件。

# 在文件中，添加以下内容:

name: Sync with upstream

on:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch upstream changes
        run: git fetch upstream master

      - name: Merge upstream changes
        run: git merge upstream/master --no-ff

      - name: Push changes
        run: git push origin master

      - name: Create a release
        uses: softprops/action-gh-release@v1
        if: ${{ github.event.schedule.cron }}
        with:
          tags: "v1.0.0"
          name: "Monthly Sync"
          body: "This is a monthly sync release."
